### ISSUE TITLE
Incomplete QuickTime support: unhandled 'pnot' and 'PICT' atom tags

### ISSUE THREAD

**Issue by dplanella** [freevo/kaa-metadata#1]
My Pentax camera produces QuickTime videos that fail to be read by kaa.metadata due to them including 'pnot' and associated 'PICT' atoms that contain preview data as per the [QuickTime format spec](https://github.com/freevo/kaa-metadata/blob/master/src/video/mp4.py#L201).

Looking at the [code](http://developer.apple.com/library/mac/#documentation/quicktime/qtff/QTFFChap1/qtff1.html), it seems that they are simply ignored, which causes a ParseError.

**Comment by Dischi** [comment]
Closed by issue #2
