### ISSUE TITLE
infinite loop decoding corrupted quicktime movie

### ISSUE THREAD

**Issue by tonio75** [freevo/kaa-metadata#2]
If a mdat, skip, pnot, PICT block is declared as 0 size, the mp4 decoder is stuck in an infinite loop.

The faulty media comes from my DSLR which sometimes produces corrupted data. (file available on demand).

The loop in question is found at MPEG4.**init** : 

```
    while type in ('mdat', 'skip', 'pnot', 'PICT'):
        # movie data at the beginning, skip
        file.seek(size-8, 1)
        h = file.read(8)
        (size,type) = struct.unpack('>I4s',h)
```

Appending the condition "and size > 0" makes the decoder fails in a better way.

+++

**Comment by Dischi** [comment]
Fixed. I also added 'pnot', 'PICT' from your loop.
