### ISSUE TITLE
cdrommodule.c fails to compile on Mac OS X

### ISSUE THREAD

**Issue by grav** [freevo/kaa-metadata#3]
I get a lot of compile errors from this particular file (see below).

If I stub out the functions (returning NULL), the package will install.

$ sudo python setup.py install
Warning: libdvdread is missing.
The DVD parser will be disabled
running install
running build
running build_py
running build_ext
building 'kaa/metadata/disc/_cdrom' extension
cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -mno-fused-madd -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/disc/cdrommodule.c -o build/temp.macosx-10.9-intel-2.7/src/disc/cdrommodule.o -Wall
clang-real: warning: argument unused during compilation: '-mno-fused-madd'
src/disc/cdrommodule.c:101:35: error: variable has incomplete type 'struct cdrom_tochdr'
    struct CDDB_TOC_HEADER_STRUCT hdr;
                                  ^

**Comment by cyphunk** [comment]
had the same issue. replace cdrommodule with: http://cddb-py.sourceforge.net/CDDB/unix/cdrommodule.c

compiles fine then

**Comment by siliceo** [comment]
@cyphunk Your suggestion worked for me (running Mac OS X --10.7.5 and Python 2.7) A link to your answer should be included on the http://cddb-py.sourceforge.net/ page. Hopefully by including the link in this post will help folks to find your answer. Thanks!

**Comment by Dischi** [comment]
cdrommodule is not supported in the Python 3 (deprecated, I have no drive anymore)
